apiVersion: route.openshift.io/v1
kind: Route
metadata: 
  labels: 
    app.kubernetes.io/instance: testnewgoproj
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: testnewgoproj 
  name: testnewgoproj
spec:
  port:
    targetPort: 8081 
  tls:
    insecureEdgeTerminationPolicy: Redirect
    termination: edge
  to:
    kind: Service
    name: testnewgoproj
    weight: 100 
